scale: 1
metatile: 1
name: "Transilien Network"
bounds:
  - 1.395263671875
  - 48.111099041065366
  - 3.592529296875
  - 49.24629332459796
center:
  - 2.5722
  - 48.8028
  - 10
format: "png"
interactivity: false
minzoom: 9
maxzoom: 15
srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
Stylesheet:
  - "style.mss"
Layer:
  - id: "land"
    name: "land"
    class: ""
    geometry: "polygon"
    extent:
      - -180
      - -85.05112877980659
      - 180
      - 85.05112877980659
    srs-name: "900913"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
    Datasource:
      file: "http://data.openstreetmapdata.com/simplified-land-polygons-complete-3857.zip"
      type: "shape"
    advanced: {}
  - id: "landuse"
    name: "landuse"
    class: ""
    geometry: "polygon"
    extent:
      - -180
      - -85.05112877980659
      - 180
      - 85.05112877980659
    srs-name: "900913"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
    Datasource:
      dbname: idf
      geometry_field: way
      type: postgis
      extent: -20037508,-19929239,20037508,19929239
      table: |- 
        ( SELECT
            way, way_area AS area, COALESCE(landuse, leisure, "natural") AS type,
            tags->'landfill:type' as landfill_type
          FROM
            planet_osm_polygon
          WHERE
            way_area > 1000000
            AND (landuse IS NOT NULL OR leisure IS NOT NULL or "natural" IS NOT NULL)
          ORDER BY
            way_area DESC
        ) AS data
  - id: waterway
    name: waterway
    class: ""
    geometry: polygon
    extent:
      - -180
      - -85.05112877980659
      - 180
      - 85.05112877980659
    srs-name: "900913"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
    Datasource:
      dbname: idf
      geometry_field: way
      type: postgis
      extent: -20037508,-19929239,20037508,19929239
      table: |-
        ( SELECT
            way, "natural" AS type, way_area AS area
          FROM
            planet_osm_polygon
          WHERE
            ("natural"='water' AND way_area > 10000)
            OR
            waterway IN ('basin', 'canal', 'riverbank', 'lock')
          ) AS data
  - id: boundary
    name: boundary
    class: ""
    geometry: polygon
    extent:
      - -180
      - -85.05112877980659
      - 180
      - 85.05112877980659
    srs-name: "900913"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
    Datasource:
      dbname: idf
      geometry_field: way
      type: postgis
      extent: -20037508,-19929239,20037508,19929239
      table: |-
        ( SELECT
            way, admin_level::integer
          FROM
            planet_osm_roads
          WHERE
            "boundary"='administrative'
            AND (admin_level IN ('6','8','9') OR (admin_level='4' AND tags->'ref:INSEE'='11'))
            AND "boundary" IS NOT NULL
            AND osm_id<0
          ORDER BY
            admin_level DESC
        ) AS data
  - id: railway
    name: railway
    class: ""
    geometry: linestring
    extent:
      - -180
      - -85.05112877980659
      - 180
      - 85.05112877980659
    srs-name: "900913"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
    Datasource:
      dbname: idf
      geometry_field: way
      type: postgis
      extent: -20037508,-19929239,20037508,19929239
      table: |-
        ( SELECT
            way
          FROM
            planet_osm_line
          WHERE
            tags->'network' IN('Transilien', 'RER')
            AND osm_id<0
            AND (railway IS NOT NULL OR route IS NOT NULL)
          ORDER BY
            z_order
        ) AS rail
  - id: place
    name: place
    class: ""
    geometry: point
    extent:
      - -180
      - -85.05112877980659
      - 180
      - 85.05112877980659
    srs-name: "900913"
    srs: "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0.0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs +over"
    Datasource:
      dbname: idf
      geometry_field: way
      type: postgis
      extent: -20037508,-19929239,20037508,19929239
      table: |-
        ( SELECT
            way,
            CASE WHEN place='city' THEN 1 WHEN place='town' THEN 2 ELSE 100 END as prio,
            place AS type, name, z_order, CASE WHEN population ~ E'^\\\\d{1,9}$' THEN population::integer ELSE NULL END AS population
          FROM
            planet_osm_point
          WHERE
            place IN ('city', 'town', 'village')
            AND place IS NOT NULL
          ORDER BY prio, population DESC NULLS LAST
        ) AS data
